services:
  python:
    init: true
    hostname: python
    container_name: python
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/src
    command: ["/bin/bash", "/src/run.sh"]
