services:
  rocksdb:
    init: true
    hostname: rocksdb
    container_name: rocksdb
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/src
    command: ["/bin/bash", "/src/build.sh"]
